name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
      - name: Yarn Lint
        run: yarn lint